feat: improve CI by generating code and validating diffs
Signed-off-by: Alexandre Lamarre <alex7285@gmail.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -34,5 +34,14 @@ jobs:
           go-version: '1.24'
       - name : Build
         run : make build
+      - name : Generate
+        run : go generate ./...
+      - name: Validate no file changes
+        run: |
+            if [[ -n "$(git status --porcelain)" ]]; then
+            echo "Error: Uncommitted changes detected."
+            git status
+            exit 1
+            fi
       - name : Test
         run : go test -v -timeout 30s -race ./...
